# Build project: docker-compose build
# Run command: docker-compose up

version: '3.7'

services:
  backend:
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    command: python3 /chatbot/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/chatbot
    ports:
      - 8000:8000
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm start --prefix /chatbot/frontend
    volumes:
      - .:/chatbot
    ports:
      - 3000:3000